# Generated by Django 5.2.6 on 2025-10-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
    ]
