# Generated by Django 5.2.7 on 2025-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False, help_text="Подтверждён ли email пользователя", verbose_name="Email подтверждён"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда был создан токен подтверждения",
                null=True,
                verbose_name="Дата создания токена",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Уникальный токен для подтверждения email",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Токен подтверждения",
            ),
        ),
    ]
