# Generated by Django 5.2.7 on 2025-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_email_verified_user_token_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                help_text="Уникальный токен для подтверждения email",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Токен подтверждения",
            ),
        ),
    ]
