# Generated by Django 5.2.7 on 2025-10-05 19:51

from django.db import migrations


def mark_existing_users_as_verified(apps, schema_editor):
    """
    Data migration: устанавливаем is_email_verified=True для всех существующих пользователей.

    Это необходимо для того, чтобы пользователи, созданные до внедрения email verification,
    могли продолжать пользоваться системой без необходимости подтверждения email.
    """
    User = apps.get_model("users", "User")
    User.objects.filter(is_email_verified=False).update(is_email_verified=True)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: не делаем ничего, так как мы не можем безопасно откатить это изменение.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_verification_token"),
    ]

    operations = [
        migrations.RunPython(mark_existing_users_as_verified, reverse_migration),
    ]
