# Generated by Django 5.2.6 on 2025-09-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Группа")),
            ],
            options={
                "verbose_name": "группа",
                "verbose_name_plural": "группы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("first", "Первый курс"),
                            ("second", "Второй курс"),
                            ("third", "Третий курс"),
                            ("fourth", "Четвертый курс"),
                        ],
                        default="first",
                        max_length=6,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="students", to="students.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "студент",
                "verbose_name_plural": "студенты",
                "ordering": ["last_name"],
            },
        ),
    ]
