# Generated by Django 5.2.7 on 2025-10-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_email_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["last_name"],
                "permissions": [
                    ("can_promote_student", "Can promote student"),
                    ("can_expel_student", "Can expel student"),
                ],
                "verbose_name": "студент",
                "verbose_name_plural": "студенты",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="students", to="students.group"
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=100)),
                ("score", models.FloatField()),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="students.student")),
            ],
        ),
    ]
