# Generated by Django 5.2.7 on 2025-10-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Может отменять публикацию продукта")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
