# Generated by Django 5.2.7 on 2025-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Ошибка")],
                        help_text="Результат попытки отправки",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Технический ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ сервера",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда была выполнена попытка отправки",
                        verbose_name="Дата попытки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при каждом сохранении",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Флаг для мягкого удаления - неактивные объекты можно не показывать",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Когда начать рассылку", verbose_name="Дата и время начала"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="Когда завершить рассылку", verbose_name="Дата и время окончания"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("running", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        help_text="Текущий статус рассылки",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
                "permissions": [("can_disable_mailing", "Может отключать рассылки")],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при каждом сохранении",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Флаг для мягкого удаления - неактивные объекты можно не показывать",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Тема email сообщения", max_length=255, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(help_text="Содержание email сообщения", verbose_name="Текст письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при каждом сохранении",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Флаг для мягкого удаления - неактивные объекты можно не показывать",
                        verbose_name="Активен",
                    ),
                ),
                ("email", models.EmailField(help_text="Email адрес получателя", max_length=254, verbose_name="Email")),
                ("full_name", models.CharField(help_text="ФИО получателя", max_length=255, verbose_name="Полное имя")),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о получателе",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["full_name"],
            },
        ),
    ]
