# Generated by Django 5.2.7 on 2025-10-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший этот объект",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(
                help_text="К какой рассылке относится попытка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший этот объект",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                help_text="Сообщение для отправки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailings.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший этот объект",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Получатели рассылки",
                related_name="mailings",
                to="mailings.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipient",
            unique_together={("email", "owner")},
        ),
    ]
