# Generated by Django 5.2.7 on 2025-10-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Кому отправлялось письмо",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.recipient",
                verbose_name="Получатель",
            ),
        ),
    ]
