# Generated by Django 5.2.7 on 2025-10-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_attempt_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
