# Generated by Django 5.2.7 on 2025-10-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_message_options_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
