# Generated by Django 5.2.7 on 2025-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_add_can_view_all_mailings_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную (веб-интерфейс)"),
                    ("scheduled", "Автоматически (по расписанию)"),
                    ("command", "Команда (management command)"),
                ],
                default="manual",
                help_text="Как была запущена рассылка",
                max_length=20,
                verbose_name="Способ запуска",
            ),
        ),
    ]
