# Generated by Django 5.2.7 on 2025-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_add_trigger_type_to_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="successfully_sent",
            field=models.BooleanField(
                default=False,
                help_text="Флаг успешной отправки рассылки всем получателям",
                verbose_name="Успешно отправлена",
            ),
        ),
    ]
