# Generated by Django 5.2.7 on 2025-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_mailing_successfully_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="run_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Номер запуска рассылки (для отслеживания повторных отправок)",
                verbose_name="Номер запуска",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="current_run",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Номер текущего запуска рассылки (увеличивается при повторной отправке)",
                verbose_name="Текущий запуск",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Флаг активности рассылки (менеджеры могут отключать)", verbose_name="Активна"
            ),
        ),
    ]
