# Generated by Django 5.2.7 on 2025-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение для записи блога",
                null=True,
                upload_to="blogs/previews/",
                verbose_name="Превью",
            ),
        ),
    ]
