# Generated by Django 5.2.7 on 2025-10-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="owner",
            field=models.ForeignKey(
                default=blog.models.get_deleted_user,
                help_text="Пользователь, создавший запись",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
