# Generated by Django 5.2.7 on 2025-10-18 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_unpublish_post", "Может отменять публикацию записи блога")],
                "verbose_name": "запись блога",
                "verbose_name_plural": "записи блога",
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="owner",
            field=models.ForeignKey(
                default=1,
                help_text="Пользователь, создавший запись",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
